Update action-bar.md
NativeScript/docs-v7 pull request #1028
Opened 2017-12-29 14:47 UTC by rajatraj733

Website androiddrawables.com is not working. But, I could not find the alternative website. 
The website https://developer.android.com/reference/android/R.drawable.html seemed to me the one which should be followed for the system icons, but this page did not display the icons corresponding to the icon name.

2018-01-02 08:40 UTC, etabakov commented
run ci

2018-01-02 09:51 UTC, vakrilov requested changes
Thanks for the PR @rajatraj733 
Too bad `androiddrawables.com` in no longer available.
Having no link with list os available values will just leave you wondering how to use the `android.systemIcon` property. Can you add in a link to ` https://developer.android.com/reference/android/R.drawable.html `. It seems good enough.

2018-01-02 17:27 UTC, rajatraj733 commented
@vakrilov I have made the changes. If it requires more modification, ask me to do the same otherwise merge the pull request.

2018-01-04 13:03 UTC, etabakov approved these changes
Thanks for your effort and contribution!

2018-01-04 13:04 UTC, merged