Added DocLayout to the list
NativeScript/docs-v7 pull request #1037
Opened 2018-01-12 14:01 UTC by rakeshgirase

Added DocLayout to the list

2018-01-15 06:32 UTC, etabakov requested changes
Thanks for the addition! Just a small typo to fix and your request is ready to be merged.

2018-01-15 06:32 UTC, etabakov commented on docs/core-concepts/modules.md
> ++ [ui/layouts/dock-layout]({%ns_cookbook ui/layouts/dock-layout%}): Provides the `DocLayout` class which lets you arrange the children of the layout at top, bottom, left and right of the layout.
There is a typo in "DocLayout".

2018-01-19 09:49 UTC, rakeshgirase commented
Done the changes.

2018-01-19 13:38 UTC, etabakov commented
Actually, the correct one is the other way around. DockLayout instead of DocLayout.

2018-01-19 17:55 UTC, etabakov approved these changes

2018-01-19 17:56 UTC, etabakov commented
Thank you very much for your effort!

2018-01-19 17:56 UTC, etabakov commented
run ci

2018-01-19 17:57 UTC, merged