feat: add upgrade instructions for Webpack, Angular and TypeScript
NativeScript/docs-v7 pull request #1242
Opened 2018-07-04 13:31 UTC by NickIliev

Related to [https://github.com/NativeScript/docs/issues/1172](https://github.com/NativeScript/docs/issues/1172)

2018-07-04 13:38 UTC, sis0k0 commented on docs/releases/upgrade-instructions.md
> +- `--deps` - this flag will update all related developer dependencies.
development dependencies

2018-07-04 13:40 UTC, sis0k0 requested changes

2018-07-04 13:40 UTC, sis0k0 commented on docs/releases/upgrade-instructions.md
> +The Webpack plugin is available as a npm package named [nativescript-dev-webpack](https://www.npmjs.com/package/nativescript-dev-webpack). To use the plugin in your project, you should explicitly ins
Maybe word it as the `nativescript-dev-webpack` plugin instead of the `webpack` plugin? The same goes for `angular` and `typescript`.

2018-07-04 13:40 UTC, sis0k0 commented on docs/releases/upgrade-instructions.md
> +- `--deps` - this flag will update all related developer dependencies.
development dependencies

2018-07-04 13:40 UTC, sis0k0 commented on docs/releases/upgrade-instructions.md
> +npm i
`--deps` will do `npm i` automatically, so this is not needed.

2018-07-04 13:40 UTC, sis0k0 commented on docs/releases/upgrade-instructions.md
> +When upgrading an existing version of the Webpack plugin, you should consider that the related developer dependencies also have to be updated accordingly. To ease the process, the plugin provides an
`ns-update-webpack` -> `update-ns-webpack`

2018-07-05 07:08 UTC, NickIliev commented on docs/releases/upgrade-instructions.md
> +The Webpack plugin is available as a npm package named [nativescript-dev-webpack](https://www.npmjs.com/package/nativescript-dev-webpack). To use the plugin in your project, you should explicitly ins
The context :

The Webpack plugin is available as a npm package named  **`nativescript-dev-webpack`**.

Wouldn/t it be strange to say:

The `nativescript-dev-webpack` plugin is available as a npm package named  **`nativescript-dev-webpack`**.

2018-07-05 07:47 UTC, sis0k0 approved these changes

2018-07-05 07:59 UTC, tsonevn approved these changes

2018-07-05 10:13 UTC, merged