docs(webpack): add custom application and activity section
NativeScript/docs-v7 pull request #1254
Opened 2018-07-10 06:33 UTC by vchimev

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the new state of the documentation article?
Add custom application and activity configuration information.

Describes https://github.com/NativeScript/nativescript-dev-webpack/issues/564#issuecomment-399675425.

2018-07-10 08:24 UTC, etabakov reviewed
Some minor issues ...

2018-07-10 08:24 UTC, etabakov commented on docs/performance-optimizations/bundling-with-webpack.md
> +If your project extends android application, it should be added as an [entry](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/demo/AngularApp/webpack.config.js#L71) to the `webpa
- "extends android application" should be "extends an Android application"

2018-07-10 08:24 UTC, etabakov commented on docs/performance-optimizations/bundling-with-webpack.md
> +The `application.js` bundle file is independent of the `bundle.js` and `vendor.js` files and the reason for it is that they are not loaded so early in the application launch. That's why the logic in
- "the reason for it" would sound better as "the reason for this/that"

2018-07-10 08:24 UTC, etabakov commented on docs/performance-optimizations/bundling-with-webpack.md
> +If your project extends android activity, it should be added to the [`appComponents`](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/demo/AngularApp/webpack.config.js#L19) array
- again "extends an Android activity"

2018-07-10 08:24 UTC, etabakov commented on docs/performance-optimizations/bundling-with-webpack.md
> +In this way and With the default config, these components [get](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/demo/AngularApp/webpack.config.js#L109-L116) in the common *vendor
- not sure why "With" is capitalized
 - a typo in "android-app-comopnents-loader"

2018-07-16 11:40 UTC, sis0k0 requested changes
I think these sections should be part of the docs article for extending application and activity. The webpack article can link to the sections in the other article.

2018-07-17 15:15 UTC, sis0k0 approved these changes

2018-07-17 15:44 UTC, merged