docs: Add the code-sharing section
NativeScript/docs-v7 pull request #1288
Opened 2018-07-31 17:20 UTC by sebawita

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?

## What is the new state of the documentation article?
Adding code sharing section.

2018-07-31 18:08 UTC, etabakov commented on docs/code-sharing/building-code-sharing-apps.md
> +# Build Process
In order a markdown file to be processed by Jekyll, it needs to have a "front matter", which is basically a valid YAML data surrounded by triple dashes. It contains some meta information for the article. Example:

```
---
title: Build Process
description: <put here a some short summary of what this article is about>
position: <used for ordering of the articles on folder level>
slug: <optional, friendly name by which you can refer the article>
---
```
You can take a look at this md for example: https://raw.githubusercontent.com/NativeScript/docs/master/docs/core-concepts/accessing-native-apis-with-javascript.md

By doing this, you don't need to specify every single article in the config.yml. Only the `code-sharing` entry should stay in order to set a title for the folder itself. Its children will use the properties provided in their own markdowns.

2018-07-31 18:49 UTC, sis0k0 commented on docs/code-sharing/building-code-sharing-apps.md
> +Webpack checks **VFS** for the `.tns` file first (in this case `my.component.tns.ts`) and serves the **NativeScript specific** file, if not it provides the shared file.
We can mention that `.android` and `.ios` files are also included in these checks.

2018-07-31 18:49 UTC, sis0k0 commented on docs/code-sharing/code-splitting.md
> +There is a simple a naming convention that allows you to provide two versions of the same file. All you need to do is create two files and add `.tns` before file extension to one of them, i.e.
`There is a simple a naming convention`
->
`There is a simple naming convention`

2018-07-31 18:49 UTC, sis0k0 commented on docs/code-sharing/code-splitting.md
> +When you run `tns run [ios/android] --bundle` webpack will take all NativeScript specific files and rename them by removing the `.tns` part. For example: `name.component.tns.html` will become `name.c
Something is missing here.

2018-07-31 18:49 UTC, sis0k0 commented on docs/code-sharing/code-splitting.md
> +export class DrawerHelper {
Make this a service. For example:

2018-08-01 11:45 UTC, etabakov commented on docs/code-sharing/build-process.md
> +previous_url: /migrating-a-web-project
The "previous_url" property is used to add redirects when an article has been moved to a new location. As this is a new section, you don't need it for any of the articles.

2018-08-01 11:46 UTC, etabakov commented on docs/code-sharing/build-process.md
> +slug: code-sharing
The slug should be unique per article I think. If you are not using it, you can just skip it.

2018-08-01 11:57 UTC, sis0k0 commented on docs/code-sharing/code-splitting.md
> +When building a project with code sharing project you will share a big part of the code, however you will encounter situations where you need to provide different code for the web app and for the mob
2 projects -> 2 project ;d

2018-08-01 11:57 UTC, sis0k0 commented on docs/code-sharing/code-splitting.md
> +There is a simple a naming convention that allows you to provide two versions of the same file. All you need to do is create two files and add **.tns** before file extension to one of them, i.e.
a simple a naming convention ->
a simple naming convention

2018-08-01 11:57 UTC, sis0k0 commented on docs/code-sharing/code-splitting.md
> +When you run **ng serve**, all **.tns** files should be **treeshaked** and as a result removed, so they won't affect the web app code.
I would suggest to reword this like:
```
no **.tns** files will be bundled
```

2018-08-01 11:57 UTC, sis0k0 commented on docs/code-sharing/code-splitting.md
> +When you run **tns run [ios/android] --bundle** webpack will take all NativeScript specific files and rename them by removing the **.tns** part. For example: **name.component.tns.html** will become *
Maybe we can write as something like:

2018-08-01 12:17 UTC, sis0k0 requested changes

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/creating-a-new-project.md
> +Creating a code sharing project is a straight forwards process. You can use Angular CLI and NativeScript schematics to generate a brand new project with a code sharing setup.
straightforward?

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/creating-a-new-project.md
> + * **style.css** - stylesheet for the web app
style.css -> styles.css

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/creating-a-new-project.md
> +By default, all projects will be generated with **NativeScript Core Theme**.
Maybe mention that this a styling theme and add link to the docs article / github repo.

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/intro.md
> +The Angular and NativeScript teams teamed up to create [nativescript-schematics](https://github.com/nativescript/nativescript-schematics), a schematic that enables you to build both web and mobile ap
a schematic -> a schematic collection?

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/migrating-a-web-project.md
> +## Project Requirements
I would suggest adding also `Environment Requirements` and links to the {N} setup article.

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/migrating-a-web-project.md
> +The process here is that you should add navigation paths to **routes** array in **app-routing.module.ts**, as you migrate each of your components.
**app-routing.module.ts** -> **app-routing.module.tns.ts**

as you migrate each of your components -> as you migrate each of your **page** components.

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/migrating-a-web-project.md
> +You should also migrate your **NgModules** into a code sharing modules.
a code sharing modules. -> code sharing modules.

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/migrating-a-web-project.md
> +### Schematic: migrate-component
I think this section should be right after the `Migrating components` section.

2018-08-01 12:17 UTC, sis0k0 commented on docs/code-sharing/platform-specific-components.md
> +You just need to exclude the component from **NativeScript's AOT TypeScript Config** (**tsconfig.aot.json**), for example:
You should also make sure that this file is not imported in any other TS file that's part of the web build. For example, it may imported in a `spec` file.

2018-08-01 13:05 UTC, sebawita commented on docs/code-sharing/code-splitting.md
> +export class DrawerHelper {
Wouldn't creating a service and injecting it be a bit of an overkill?
Do you think it would be worth to present two different approaches?

* the one with the helper file
* one with a service

2018-08-01 13:14 UTC, sis0k0 commented on docs/code-sharing/code-splitting.md
> +export class DrawerHelper {
I would prefer DI, because you can mock the service without depending on the `.tns` extension only. @vakrilov, what do you think?

2018-08-01 13:15 UTC, sebawita commented on docs/code-sharing/code-splitting.md
> +When you run **tns run [ios/android] --bundle** webpack will take all NativeScript specific files and rename them by removing the **.tns** part. For example: **name.component.tns.html** will become *
how about this?

When you run **tns run [ios/android] --bundle** **.tns** files will be bundled instead of the web files.

2018-08-01 13:27 UTC, sebawita commented on docs/code-sharing/migrating-a-web-project.md
> +## Project Requirements
hmmm... I might need your help here

2018-08-01 15:02 UTC, vakrilov commented on docs/code-sharing/code-splitting.md
> +export class DrawerHelper {
I think service is definitely the more Angular-ish way. if it is gonna be in a separate file - why not just make it a service. The added price you would have to pay is to register it in a module.

2018-08-02 08:12 UTC, sis0k0 approved these changes

2018-08-02 08:26 UTC, dtopuzov commented
test

2018-08-02 12:39 UTC, NickIliev commented on docs/code-sharing/intro.md
> +Read about [Creating a New Project](/angular/code-sharing/creating-a-new-project) to get started.
The link `(/angular/code-sharing/creating-a-new-project)` is broken on my side.
Using `(./creating-a-new-project)` will do the trick

2018-08-02 17:29 UTC, sebawita commented on docs/code-sharing/intro.md
> +Read about [Creating a New Project](/angular/code-sharing/creating-a-new-project) to get started.
well spotted :)
fixed

2018-08-03 14:27 UTC, merged