docs: webpack debugging sections added
NativeScript/docs-v7 pull request #1295
Opened 2018-08-03 14:45 UTC by NickIliev

Webpack debug steps for Chrome DevTools and for VSCode added in the related sections.

2018-08-04 11:07 UTC, sis0k0 requested changes

2018-08-04 11:07 UTC, sis0k0 commented on docs/tooling/debugging/chrome-devtools.md
> +For security reasons,genearated the debugging agent **can't be started automatically** from the command-line. That's why NativeScript CLI **generates a URL** which is printed on the screen instead.
genearated -> generated

2018-08-04 11:07 UTC, sis0k0 commented on docs/tooling/debugging/chrome-devtools.md
> +Examplgenerated URL
Examplgenerated URL -> Example generated URL

2018-08-04 11:07 UTC, sis0k0 commented on docs/tooling/debugging/chrome-devtools.md
> +To start debugging, open the following URL in Chrome:
I think one of the two sentences is enough.

2018-08-04 11:07 UTC, sis0k0 commented on docs/tooling/debugging/debugging.md
> +* `--bundle` - Provides debugging functionality for Webpack bundled applications.
More like - builds the app with webpack before starting the debugger or sth like that.

2018-08-04 11:07 UTC, sis0k0 commented on docs/tooling/visual-studio-code-extension.md
> +Choose one of the launch configurations (e.g., `Launch on iOS`) and press the `Start Debugging` button next to the menu. This will trigger a NativeScript CLI command which will build, deploy and run
functionallity -> functionality

2018-08-04 11:07 UTC, sis0k0 commented on docs/tooling/visual-studio-code-extension.md
> +Note that the `nativescript-dev-webpack` will autogenerate the `sourceMapPathOverrides` key.
The VSCode extension generates that key.

2018-08-06 08:02 UTC, tsonevn approved these changes

2018-08-06 08:03 UTC, tsonevn commented
test

2018-08-06 08:03 UTC, merged