docs: improvements to the code-sharing section
NativeScript/docs-v7 pull request #1308
Opened 2018-08-13 17:41 UTC by sebawita

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the new state of the documentation article?
Added more content for the code-sharing docs

Fixes/Implements/Closes #[Issue Number].
n/a

2018-08-13 18:46 UTC, sis0k0 requested changes

2018-08-13 18:46 UTC, sis0k0 commented on docs/code-sharing/intro.md
> +* **updateItemQuantity** - allows to change the quantity of a given item in the basket
maybe remove `allows to` in order to follow the same format as the other items in the list.

2018-08-13 18:46 UTC, sis0k0 commented on docs/code-sharing/intro.md
> +The **Basket Service** should be made of 100% shared code
shared -> shareable / platform-agnostic ?

2018-08-13 18:46 UTC, sis0k0 commented on docs/code-sharing/intro.md
> +The **Basket Service** should be made of 100% shared code
Also add a dot at the end of the sentence.

2018-08-13 18:46 UTC, sis0k0 commented on docs/code-sharing/intro.md
> +Again, the **PaymentService** should be made of 100% shared code
The same as the above comments.

2018-08-13 18:46 UTC, sis0k0 commented on docs/code-sharing/intro.md
> +Next, you would need to create a component, that would consume the **Basket** and the **Payment** services, and allow users to:
consume -> inject

2018-08-13 18:46 UTC, sis0k0 commented on docs/code-sharing/intro.md
> +In this case the UI for the web and mobile apps is going to be different, and as a result the template code **cannot be shared**. However, everything underneath that drives it's behaviour is still sh
it's behaviour -> its behaviour

2018-08-13 18:46 UTC, sis0k0 commented on docs/code-sharing/intro.md
> +Even though, the contents of **basket.component.html** and **basket.component.tns.html** is not quite the same, you can see that in general they follow the same structure. Both use the **async pipe**
the contents ... is -> the contents ... are

2018-08-14 05:52 UTC, sis0k0 approved these changes

2018-08-14 07:42 UTC, etabakov approved these changes

2018-08-14 13:36 UTC, merged