change App id article
NativeScript/docs-v7 pull request #1397
Opened 2018-10-12 10:59 UTC by tsonevn

change App id article

2018-10-12 11:24 UTC, NickIliev approved these changes

2018-10-16 10:39 UTC, KristianDD requested changes
Maybe you can add that if the user doesn't need different id-s for each platform, he can leave it as a string value.

2018-10-16 10:39 UTC, KristianDD commented on docs/tooling/changing-appid.md
> +description: Learn how change the application identifire(App ID) in the NativeScript application for both platforms(iOS/Android).
identifier

2018-10-16 10:39 UTC, KristianDD commented on docs/tooling/changing-appid.md
> +The App ID is a unique string, which contain two or more strings, separated by a dot. It is used to identify your app on the device and in the store(iTunes Store / Google Play Store), where it is pub
I am not sure about the term "iTunes ID". Haven't found any information that this exists. There is App ID and Bundle ID. The App ID is a combination of the Team ID and Bundle ID. Our application identifier is actually representing the Bundle ID.([source](https://developer.apple.com/library/archive/documentation/General/Conceptual/DevPedia-CocoaCore/AppID.html))
Also didn't find any information on the term "Google Play ID". The variable is called "application ID" - more information [here](https://developer.android.com/studio/build/application-id).
"for the **initially** App ID" ->  "for the **initial** App ID" might also add example like ("org.nativescript.{appName}")

2018-10-16 10:39 UTC, KristianDD commented on docs/tooling/changing-appid.md
> +From NativeScript(v.5.0) we can change the App ID using the project's `package.json` file while specifying a unique string for iOS and Android. Follow the below-attached steps to change the identifie
NativeScript(v.5.0) -> NativeScript(v5.0.0).

2018-10-16 11:23 UTC, KristianDD approved these changes
I still think that we should add that the new structure is needed only if the user needs different app id for the platforms.
```
"nativescript": {
    "id": {
        "ios": "{{appID1}}" ,
        "android": "{{appID2}}"
    }
  }
```
or 
```
"nativescript": {
    "id": "{{appID}}"
}
```

2018-10-17 15:00 UTC, etabakov commented on docs/tooling/changing-appid.md
> +The App ID is a unique string, which contain two or more strings, separated by a dot. It is used to identify your app on the device and in the store(iTunes Store / Google Play Store), where it is pub
I think the appId cannot start with number as well, at least for Android

2018-10-17 15:01 UTC, etabakov commented on docs/tooling/changing-appid.md
> +2.  If you are using old project, open `<project_name>/App_Resources/Android/app.gradle` file and remove the `applicationId` key.
Let's state explicitly what "old" means. Before 5.0 I presume.

2018-10-18 07:24 UTC, etabakov approved these changes
Looks great, just some whitespaces before opening brackets.

2018-10-18 07:24 UTC, etabakov commented on docs/tooling/changing-appid.md
> +The App ID is a unique string, which contain two or more strings, separated by a dot. It is used to identify your app on the device and in the store(iTunes Store / Google Play Store), where it is pub
```suggestion
The App ID is a unique string, which contain two or more strings, separated by a dot. It is used to identify your app on the device and in the store (iTunes Store / Google Play Store), where it is published. The application identifier refers to the Bundle ID for iOS and application ID - Android based on the mobile OS the app is built for. Each string must start with a letter and should contain only letters and numbers. The app identifier must not begin with an uppercase letter or number. In NativeScript we will use the project name, which is set, while executing the create command (`tns create <project_name>`), for the initial App ID (e.g. `org.nativescript.{appName}`).  
```

2018-10-18 07:24 UTC, etabakov commented on docs/tooling/changing-appid.md
> +From NativeScript(v5.0.0) we can change the App ID using the project's `package.json` file while specifying a unique string for iOS and Android. Follow the below-attached steps to change the identifi
```suggestion
From NativeScript (v5.0.0) we can change the App ID using the project's `package.json` file while specifying a unique string for iOS and Android. Follow the below-attached steps to change the identifier:
```

2018-10-18 07:24 UTC, etabakov commented on docs/tooling/changing-appid.md
> +2.  If you are using project, created before NativeScript(v5.0.0), open `<project_name>/App_Resources/Android/app.gradle` file and remove the `applicationId` key.
```suggestion
2.  If you are using project, created before NativeScript (v5.0.0), open `<project_name>/App_Resources/Android/app.gradle` file and remove the `applicationId` key.
```

2018-10-23 12:55 UTC, tsonevn commented
test

2018-11-02 13:32 UTC, merged