Fix scroll sidebar docs
NativeScript/docs-v7 pull request #1492
Opened 2019-01-02 22:49 UTC by bdlb77

## PR Checklist

- [x ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?

   #1455 , implemented scroll effect for both left and right sidebars. Both sidebars didn't have the ability to scroll on content, causing difficulty in UX and navigation on tabs. 

## What is the new state of the documentation article?

  The side navbars should have the ability to scroll to allow for easier access to tabs. Also they are now sticky on the page to always show and have access to their navigations.
Fixes/Implements/Closes #[Issue Number].

Fixes #1455

2019-01-03 12:39 UTC, etabakov commented
Many thanks for your effort. While reviewing the suggestion I noticed a redundant scrollbar, that ideally shouldn't be there - ![check the screenshot](https://user-images.githubusercontent.com/2611328/50638107-306bde80-0f65-11e9-900c-f6ad0aeccfbc.png).

2019-01-03 14:00 UTC, bdlb77 commented
I found a solution for the navbar that possibly only works for webkit and firefox.. I'm not sure how it looks on IE... maybe y'all have a suggestion on how to implement a fix for it there too :) Thank you guys for this opportunity! 
<img width="1440" alt="screen shot 2019-01-03 at 2 58 16 pm" src="https://user-images.githubusercontent.com/32174912/50641415-213a6000-0f68-11e9-9f09-062e19829729.png">
<img width="1440" alt="screen shot 2019-01-03 at 2 58 23 pm" src="https://user-images.githubusercontent.com/32174912/50641418-24355080-0f68-11e9-868d-c946649a67ab.png">

2019-01-04 16:40 UTC, bundyo requested changes
I hope the changes I'm requesting are not too much. 

Maybe we should have provided a design requirement beforehand. Sorry for missing that.

2019-01-04 16:40 UTC, bundyo commented on build/_assets/javascripts/app.js
> +<div class="right-nav__container navigation__right__scroll">\
You don't really need a special class for your CSS, you can just add it to ```.right-nav_container```.

2019-01-04 16:40 UTC, bundyo commented on build/_assets/javascripts/app.js
> +        function handleRightScroll(e){
This function doesn't seem needed, as you call it only once immediately after its definition.

2019-01-04 16:40 UTC, bundyo commented on build/_assets/javascripts/app.js
> +function handleScrollNav(){
The container is already sticky, not sure we need this whole implementation at all if it is done only for the transition. I would advise using only CSS - check my next comments.

2019-01-04 16:40 UTC, bundyo commented on build/_assets/javascripts/app.js
> +// Handle ns-side-scroll
I've discussed with our designer if the left side navigation should be scrollable, and we agreed that since it is part of the flow of the page and scrolls with it, this is not necessary. In addition, in the 1280 media breakpoint the menu content scrolls under the menu trigger arrow. So we should remove the scrolling of the left side navigation.

2019-01-04 16:40 UTC, bundyo commented on build/_assets/stylesheets/styles.css
> +/* Styling for the NS Side navigation scroll */
Remove these as well.

2019-01-04 16:40 UTC, bundyo commented on build/_layouts/page.html
> +            <div class="ns-side-nav"  id="ns-side-scroll" {{site.sideBarHidden}}>
I didn't really get why did you use the ID (except for styling, which you can do through the class).

2019-01-04 16:40 UTC, bundyo commented on build/_assets/stylesheets/styles.css
> +        position: sticky !important;
Avoid using important when you don't have the need to override CSS set with JS.

2019-01-04 16:40 UTC, bundyo commented on build/_assets/stylesheets/styles.css
> +.navigation__right__scroll {
After our designer saw your PR in action, we discussed how the feature should look like and decided that the scrollbar should be visible and use the **--border-light-blue color**.

No need for this class - add the overflow-y to the **.right-nav_tree** (which is used for scrolling in the 1280 breakpoint), though better use auto, to avoid showing a scrollbar when it is not needed. Instead of position: fixed, right and and bottom, add just height - something like **calc(100vh - 12.76em)** should be just right for when the yellow header is not visible and the page is not scrolled. Add also scrollbar-width: thin (instead of none) and scrollbar-color to be transparent.

Then, on hover change the scrollbar-color to the one I mentioned above. This should take care of Firefox.

I'll leave the Webkit/Chrome styling to you - make it 6px wide, transparent and the same color on hover.

Make sure to change the height when the yellow bar is visible and when the page is scrolled (the header is detached).

Also check the 1280px media breakpoint and make sure the height is still 100% when you resize to it.

2019-01-09 11:36 UTC, bdlb77 commented on build/_assets/javascripts/app.js
> +        function handleRightScroll(e){
👍

2019-01-09 11:36 UTC, bdlb77 commented on build/_assets/javascripts/app.js
> +function handleScrollNav(){
👍

2019-01-09 13:02 UTC, bdlb77 commented on build/_layouts/page.html
> +            <div class="ns-side-nav"  id="ns-side-scroll" {{site.sideBarHidden}}>
true true, I took it out!

2019-01-09 13:03 UTC, bdlb77 commented on build/_assets/stylesheets/styles.css
> +        position: sticky !important;
turned out not to be a need with this

2019-01-09 13:20 UTC, bdlb77 commented on build/_assets/stylesheets/styles.css
> +.navigation__right__scroll {
So yes you were right.. no JS needed haha..  I made this waaay too complicated than it needed to be. Thank you for the great advice! 
I'll add photos for the updated version. 

<img width="1440" alt="screen shot 2019-01-09 at 2 10 34 pm" src="https://user-images.githubusercontent.com/32174912/50901799-846d3c00-1419-11e9-9970-93fef05e4417.png">
<img width="1440" alt="screen shot 2019-01-09 at 2 10 15 pm" src="https://user-images.githubusercontent.com/32174912/50901805-8a631d00-1419-11e9-8fe7-53637d6f5e2b.png">
<img width="1440" alt="screen shot 2019-01-09 at 2 08 30 pm" src="https://user-images.githubusercontent.com/32174912/50901874-b54d7100-1419-11e9-97d8-e518ede20528.png">

2019-01-09 13:22 UTC, bdlb77 commented
So yes you were right.. no JS needed haha..  I made this waaay too complicated than it needed to be. Thank you for the great advice! 
I'll add photos for the updated version. 

<img width="1440" alt="screen shot 2019-01-09 at 2 21 45 pm" src="https://user-images.githubusercontent.com/32174912/50901972-eb8af080-1419-11e9-9489-60171f37be65.png">
<img width="1440" alt="screen shot 2019-01-09 at 2 21 37 pm" src="https://user-images.githubusercontent.com/32174912/50901973-ec238700-1419-11e9-89f2-a4662dfe575e.png">
<img width="1440" alt="screen shot 2019-01-09 at 2 21 25 pm" src="https://user-images.githubusercontent.com/32174912/50901974-ec238700-1419-11e9-99e9-25e8e4973cc5.png">


Once I do a full check again I'll push the changes

2019-01-09 13:28 UTC, bundyo commented
Thanks. 

Btw, looking at your screenshots - the colors of the scrollbar are inverted than what I had in mind - the scroll-thumb should be --border-light-blue and the scroll-track should be transparent.

2019-01-09 14:08 UTC, bdlb77 commented
<img width="1440" alt="screen shot 2019-01-09 at 3 07 49 pm" src="https://user-images.githubusercontent.com/32174912/50904364-5b9c7500-1420-11e9-893f-d414523f3243.png">
Hopefully this one will be what you were lookin for :) sorry for the confusion

2019-01-09 14:30 UTC, bdlb77 commented
I just pushed the next round of revisions :) gracias

2019-01-17 11:17 UTC, bundyo approved these changes

2019-01-17 11:18 UTC, bundyo commented
Thanks for your effort! :+1:

2019-01-17 13:04 UTC, bdlb77 commented
Thank you guys! I learned lots :)

2019-01-17 13:41 UTC, etabakov commented
Hey, thanks for your contribution! We have a special program for our first-time contributors and you are eligible to participate in it. If you haven't applied already, all you need to do to claim your prize is to fill our [Application Form](https://goo.gl/forms/lPKpXzG4F1EhfKM72).

Regards from the whole team 🥇

2019-01-17 13:41 UTC, merged