docs(core-concepts): re-work angular navigation article
NativeScript/docs-v7 pull request #1495
Opened 2019-01-08 08:08 UTC by MartoYankov

2019-01-08 09:46 UTC, etabakov approved these changes
Love it! Clear illustration and in-depth explanation of the problem as a whole. Some minor tweaks from me.

2019-01-08 09:46 UTC, etabakov commented on docs/core-concepts/angular-navigation.md
> +* `page-router-outlet` - This is an alternative to the regular `router-outlet` that serves as a placeholder for where native mobile navigation will occur.
In the bullet list above we use lower case after the dash, and in this a capital letter is used. Let's stick to one of them, I think we use lower case in most of the places.

2019-01-08 09:46 UTC, etabakov commented on docs/core-concepts/angular-navigation.md
> +NativeScript's `page-router-outlet` is the equivalent of Angular's [``router-outlet``](https://angular.io/api/router/RouterOutlet). It serves as a placeholder for native mobile navigations. Internall
Broken link

```suggestion
NativeScript's `page-router-outlet` is the equivalent of Angular's [``router-outlet``](https://angular.io/api/router/RouterOutlet). It serves as a placeholder for native mobile navigations. Internally, each `page-router-outlet` creates a NativeScript `Frame` and each component that the router displays in the outlet is wrapped in a `Page` widget. This is the main integration point that brings native navigation to Angular. The `Frame` and `Page` combination also means you can use the `ActionBar` widget in these components. For more information on how NativeScript Core navigation works visit this [documentation article]({% slug navigation %}).
```

2019-01-08 09:46 UTC, etabakov commented on docs/core-concepts/angular-navigation.md
> +* `navigate()` - This method is an alternative to the Angular `Router` [``navigate()``](https://angular.io/api/router/Router#navigate) method, but also supports navigations in a `page-router-outlet`.
Same as the first comment about the capitalisation.

2019-01-08 09:46 UTC, etabakov commented on docs/core-concepts/angular-navigation.md
> +You might want to perform some cleanup actions (e.g. unsubscribe from a service to stop updates) when you are navigating forward to a next page. If you are using `page-router-outlet` you cannot do th
Not sure if 'to' is required here, but sounds better to me at least. Feel free to disregard.

```suggestion
You might want to perform some cleanup actions (e.g. unsubscribe from a service to stop updates) when you are navigating forward to a next page. If you are using `page-router-outlet` you cannot do that in the `ngOnDestroy()` hook, as this will not be called when you navigate forward. What you can do is to inject the `Page` instance inside your component and attach to page navigation events (for example `navigatedFrom`) and do the cleanup there. You can check all the available page events [here](https://docs.nativescript.org/ui/ns-ui-widgets/page#page-events).
```

2019-01-08 09:46 UTC, etabakov commented on docs/core-concepts/angular-navigation.md
> +>**Note:** To improve the bootstrap time and the in-app navigation in large applications, Angular has introduced **lazy loading** for modules. Refer to the [Lazy Loading in NativeScript](../performan
Remove file extention in the hyperlink to avoid a redundant redirect:

```suggestion
>**Note:** To improve the bootstrap time and the in-app navigation in large applications, Angular has introduced **lazy loading** for modules. Refer to the [Lazy Loading in NativeScript](../performance-optimizations/lazy-loading) for detailed explanation and implementation steps. We won't use this feature in the following examples for the sake of simplicity.
```

2019-01-08 12:49 UTC, tsonevn approved these changes

2019-01-08 13:19 UTC, vakrilov requested changes

2019-01-08 13:19 UTC, vakrilov commented on docs/core-concepts/angular-navigation.md
> +* pageTransition - This attribute lets you specify the native transition for the `nsRouterLink` navigation. Accepted values are `true`, `false`, one of the predefined transitions listed [here](https:
Also add `pageTransitionDuration`- https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/ns-router-link.ts#L51

2019-01-08 13:19 UTC, vakrilov commented on docs/core-concepts/angular-navigation.md
> +**The Solution**: In NativeScript you can inject `PageRoute` which has an `activatedRoute: Observable<ActivatedRoute>` field inside it. Each time a new `ActivatedRoute` instance is created for this r
I think this part is severely outdated - `PageRoute` was introduced before we started using a custom route-reuse-strategy. It should not be needed now as the reuse strategy _should_ handle `activatedRoutes` correctly. 

Let's double check that and remove the reference to `PageRoute` if it not needed.

2019-01-08 14:45 UTC, vakrilov commented on docs/core-concepts/angular-navigation.md
> +**The Solution**: In NativeScript you can inject `PageRoute` which has an `activatedRoute: Observable<ActivatedRoute>` field inside it. Each time a new `ActivatedRoute` instance is created for this r
Yup - everything works with `ActivatedRoute` as expected. We can remove the whole `Passing Parameter` section from the docs as there is nothing NativeScript specific.

2019-01-09 08:24 UTC, vakrilov approved these changes
👍 Once comments are resolved.

2019-01-09 13:48 UTC, MartoYankov commented on docs/core-concepts/angular-navigation.md
> +* pageTransition - This attribute lets you specify the native transition for the `nsRouterLink` navigation. Accepted values are `true`, `false`, one of the predefined transitions listed [here](https:
I intentionally forgot to mention it :) The reason is you can set a whole `NavigationTransition` object (which contains duration) to the `pageTransition` attribute.

2019-01-09 16:02 UTC, merged