update splash on real device
NativeScript/docs-v7 pull request #1496
Opened 2019-01-08 21:05 UTC by rynop

per https://github.com/NativeScript/nativescript-cli/issues/3159

2019-01-11 14:13 UTC, etabakov requested changes
Thanks for the contribution. There are two minor suggestions from my side.

2019-01-11 14:13 UTC, etabakov commented on docs/tooling/publishing/creating-launch-screens-ios.md
> +> **WARNING**: Occasionally, the iOS operating system caches your application’s icons and launch screens. If you’re updating icons or launch screens and not seeing your changes, delete the applicatio
```suggestion
> **WARNING**: Occasionally, the iOS operating system caches your application’s icons and launch screens. If you’re updating icons or launch screens and not seeing your changes, delete the application from your device or emulator and redeploy. If on a real device: remove `platforms` folder from your project, delete app, restart device, redeploy.
```

2019-01-11 14:13 UTC, etabakov commented on docs/tooling/publishing/creating-launch-screens-ios.md
> +> **WARNING**: Occasionally, the iOS operating system caches your application’s icons and launch screens. If you’re updating icons or launch screens and not seeing your changes, delete the applicatio
There is a redundant whitespace and a typo.

2019-01-14 15:56 UTC, rynop commented on docs/tooling/publishing/creating-launch-screens-ios.md
> +> **WARNING**: Occasionally, the iOS operating system caches your application’s icons and launch screens. If you’re updating icons or launch screens and not seeing your changes, delete the applicatio
oops - yea good catch!

2019-01-17 13:45 UTC, etabakov commented on docs/tooling/publishing/creating-launch-screens-ios.md
> +> **WARNING**: Occasionally, the iOS operating system caches your application’s icons and launch screens. If you’re updating icons or launch screens and not seeing your changes, delete the applicatio
Do you mind to apply the changes suggested, so we can move this forward? Thanks!

2019-01-17 16:41 UTC, rynop commented
I committed your suggestion (d05aad2) but it still says changes requested? Any ideas?

2019-01-17 17:42 UTC, etabakov approved these changes

2019-01-17 17:43 UTC, merged

2019-01-17 17:44 UTC, etabakov commented
Thanks for the effort! We have a special program for our first-time contributors and you are eligible to participate in it. If you haven't applied already, all you need to do to claim your prize is to fill our [Application Form](https://goo.gl/forms/lPKpXzG4F1EhfKM72).

Regards from the whole team 🥇

2019-05-16 02:00 UTC, rynop commented
Hi @etabakov - filled out the app form you mentioned back in Jan, haven't gotten anything.  I love NS and would like to represent/market it....

2019-05-16 04:37 UTC, etabakov commented
Hey @rynop - sorry about that! The package that we sent to you in January was returned to us a couple of weeks ago by the postal service as undeliverable. We will resend it with the next batch in the next couple of days.

2019-05-16 13:14 UTC, rynop commented
@etabakov my bad - I must have mistyped or something.  Was going to send you correct address on linkedin via message but it won't let me connect with you.  Connect with [me](https://www.linkedin.com/in/rynop/) then I'll send you a PM with my mailing address.  LMK if that works.  I was unable to edit the application google form....