Fixed a broken link!
NativeScript/docs-v7 pull request #1525
Opened 2019-02-01 18:53 UTC by shendrekbharath

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?
 Under the docs\troubleshooting.md file we have line 93 where ./building-plugins.md link no more exists.

## What is the new state of the documentation article?
I have replaced the broken link with the right one i.e. https://github.com/NativeScript/docs/blob/master/docs/plugins/building-plugins.md

Fixes/Implements/Closes #[Issue Number].

2019-02-01 19:45 UTC, etabakov requested changes
Hey, thanks for the attempt to improve our documentation. For future contribution, please use the commit message as described [in the guidelines](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages) of the pull request.

2019-02-01 19:45 UTC, etabakov commented on docs/troubleshooting.md
> +must do so from the native part of a plugin in your app. Visit [Building Plugins](https://github.com/NativeScript/docs/blob/master/docs/plugins/building-plugins.md) for more information on how to cre
This link will point to the markdown in GitHub, instead of pointing to the article in the documentation. Here is a link with a relative path to the intended article:

```suggestion
must do so from the native part of a plugin in your app. Visit [Building Plugins](./plugins/building-plugins.md) for more information on how to create one.
```

2019-02-02 11:36 UTC, shendrekbharath commented
Hi Emil,
I have committed the changes you requested, please verify and revert. Thank
you.

Best Regards,
*Bharath *

On Sat, Feb 2, 2019 at 1:15 AM Emil Tabakov <notifications@github.com>
wrote:

> *@etabakov* requested changes on this pull request.
>
> Hey, thanks for the attempt to improve our documentation. For future
> contribution, please use the commit message as described in the guidelines
> <https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages>
> of the pull request.
> ------------------------------
>
> In docs/troubleshooting.md
> <https://github.com/NativeScript/docs/pull/1525#discussion_r253177157>:
>
> > @@ -90,5 +90,5 @@ Solution provided by [KristiyanFxy](https://github.com/KristiyanFxy) a member of
>
>
>
>  **Solution:** The 3rd party library that iOS Runtime uses to make native calls ([libffi/libffi](https://github.com/libffi/libffi/)) does
>
>  not support SIMD vectors for these 2 architectures. If your app needs to support 32-bit iOS devices and you want to consume such functions you
>
> -must do so from the native part of a plugin in your app. Visit [Building Plugins](./building-plugins.md) for more information on how to create one.
>
> +must do so from the native part of a plugin in your app. Visit [Building Plugins](https://github.com/NativeScript/docs/blob/master/docs/plugins/building-plugins.md) for more information on how to create one.
>
>
> This link will point to the markdown in GitHub, instead of pointing to the
> article in the documentation. Here is a link with a relative path to the
> intended article:
> ⬇️ Suggested change
>
> -must do so from the native part of a plugin in your app. Visit [Building Plugins](https://github.com/NativeScript/docs/blob/master/docs/plugins/building-plugins.md) for more information on how to create one.
>
> +must do so from the native part of a plugin in your app. Visit [Building Plugins](./plugins/building-plugins.md) for more information on how to create one.
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NativeScript/docs/pull/1525#pullrequestreview-199238773>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJDhyvJ-sXJOFonkIW-wR3XDWeV9wFZIks5vJJllgaJpZM4ae4kr>
> .
>

2019-02-03 08:14 UTC, etabakov approved these changes
Hey, thanks for your contribution! We have a special program for our first-time contributors and you are eligible to participate in it. If you haven't applied already, all you need to do to claim your prize is to fill our [Application Form](https://goo.gl/forms/lPKpXzG4F1EhfKM72).

Regards from the whole team 🥇

2019-02-03 08:14 UTC, merged