Extended navigation examples (nesting navigation)
NativeScript/docs-v7 pull request #1634
Opened 2019-04-22 06:56 UTC by NickIliev

An article that demonstrates a number of common scenarios for nesting forward and lateral navigations. Added schemes, description and playground demos fro TypeScript and Angular.

2019-04-22 13:09 UTC, MartoYankov requested changes

2019-04-22 13:09 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +Nesting a P-R-O inside a layout, for example, to create a secondary navigation level.
```suggestion
Nesting a P-R-O inside another page router outlet, for example, to create a secondary navigation level.
```

2019-04-22 13:09 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +Nesting a TabView (lateral navigation) inside a layout. For example in a Login component with forward navigation to a component with a nested TabView.
```suggestion
Nesting a TabView (lateral navigation) inside a page router outlet. For example in a Login component with forward navigation to a component with a nested TabView.
```

2019-04-22 13:09 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +> **TODO** iosOverflowSafeArea="false" for the nested TabView
There are some `todos` here :)

2019-04-22 13:09 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> + ## Multiple Navigation Scenarios
```suggestion
 ## Combining Nested Navigation Scenarios
```

2019-04-22 13:09 UTC, MartoYankov commented
We should also revise the images.

2019-04-23 10:33 UTC, tsonevn commented
test

2019-04-23 10:53 UTC, MartoYankov requested changes

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +    > Another Layout
```suggestion
    > Static Content
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +    > Another Layout (static place)
```suggestion
    > Static Content
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +    > Another Layout (static place)
```suggestion
    > Static Content
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +    > Another Layout (static place)
```suggestion
    > Static Content
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +Nesting simple forward navigation: a `Frame` in a layout, for example, to show an advertisement banner on the top/bottom (static place).
```suggestion
Nesting simple forward navigation: a `Frame` in a layout, for example, to show an advertisement banner on the top/bottom (static content).
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +The root page is using a layout (e.g., a `GridLayout`) as a wrapper for the nested forward navigation (`Frame`) and for the static place (layout).
```suggestion
The root page is using a layout (e.g., a `GridLayout`) as a wrapper for the nested forward navigation (`Frame`) and for the static content (layout).
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +Nesting simple forward navigation: A `page-router-outlet` (mentioned in this article also as *P-R-O*) in a layout, for example, to show an advertisement banner on the top/bottom (static place).
```suggestion
Nesting simple forward navigation: A `page-router-outlet` (mentioned in this article also as *P-R-O*) in a layout, for example, to show an advertisement banner on the top/bottom (static content).
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +title: Navigation (extended examples)
```suggestion
title: Nested Navigation
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +slug: extended-navigation
```suggestion
slug: nested-navigation
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +description: Learn how to configure your application navigation architecture, navigate forward and backward and use TabView, Modal View and SideDrawer
```suggestion
description: Learn how to nest navigation widgets and implement complex navigation scenarios
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +# Navigation Examples
```suggestion
# Nested Navigation
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +The main goal of the following article is to demonstrate some good practices for creating nested navigation structure. The article does not aim to be a strict guide, but will help you to understand h
```suggestion
The main goal of the following article is to demonstrate some good practices for creating nested navigation structure. The article does not aim to be a strict guide, but will help you to understand how you could create complex navigation structures while using forward (e.g., frames or outlets) & lateral navigation (e.g., drawers, tab views, etc.). In each of the article sections, you can find visual guides along with corresponding Playground demos.

#Simple Rule

There is one simple rule when it comes to nesting navigation widgets.

{% nativescript %}
> **Important:** When nesting a frame or a tab-view, they should never have direct siblings in the markup. Instead, wrap them in a layout and nest this layout.
{% endnativescript %}
{% angular %}
> **Important:** When nesting an outlet or a tab-view, they should never have direct siblings in the markup. Instead, wrap them in a layout and nest this layout.
{% endangular %}

If these components have siblings, they will span over them in most scenarios. The reason for this is on iOS the navigation controllers always take all the space provided by their parent regardless of their own layout parameters.

You can check out how this is done in the examples below.
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +Nesting a Frame inside a Page/Frame, for example, a secondary navigation level.
```suggestion
Nesting a Frame inside a Page/Frame, for example, a secondary navigation level.

> **Note:** Each `Frame` comes with its own `ActionBar` by default. It's typical that you want to keep one `ActionBar` on top of the screen when nesting navigations. Set the `actionBarVisibility` property of the `Frame` to `never` to hide the `ActionBar` where needed.
```

2019-04-23 10:53 UTC, MartoYankov commented on docs/core-concepts/navigation-extended.md
> +Nesting a page router outlet inside another page router outlet, for example, to create a secondary navigation level.
```suggestion
Nesting a page router outlet inside another page router outlet, for example, to create a secondary navigation level.

> **Note:** Each page router outlet comes with its own `ActionBar` by default. It's typical that you want to keep one `ActionBar` on top of the screen when nesting outlets. Set the `actionBarVisibility` property of the page router outlet to `never` to hide the `ActionBar` where needed.
```

2019-04-23 12:23 UTC, merged