Update CONTRIBUTING.md
NativeScript/docs-v7 pull request #1822
Opened 2019-10-15 08:16 UTC by sakshamtaneja21

fixed bugs

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?

## What is the new state of the documentation article?

Fixes/Implements/Closes #[Issue Number].

2019-10-15 08:32 UTC, etabakov requested changes
As the preferred spelling is American English, can you revert to "labeled" so we can accept the other changes. Thanks.

2019-10-15 08:34 UTC, etabakov commented on CONTRIBUTING.md
> +3. If this is a bug or problem that is clear, simple and is unlikely to require any discussion -- it is OK to open an issue on GitHub with a reproduction of the bug and screenshots. If possible, subm
I think the previous state was the correct usage of the Oxford comma rule.

2019-10-28 18:17 UTC, sakshamtaneja21 commented on CONTRIBUTING.md
> +3. If this is a bug or problem that is clear, simple and is unlikely to require any discussion -- it is OK to open an issue on GitHub with a reproduction of the bug and screenshots. If possible, subm
ok i got it ill add some changes and tell you

2019-10-29 08:16 UTC, etabakov approved these changes

2019-10-29 08:16 UTC, merged

2019-10-29 08:17 UTC, etabakov commented
Hey, thanks for your contribution! We have a special program for our first-time contributors and you are eligible to participate in it. If you haven't applied already, all you need to do to claim your prize is to fill our [Application Form](https://goo.gl/forms/lPKpXzG4F1EhfKM72).

Regards from the whole team 🥇