Added CLI Version and CLI Installation reference
NativeScript/docs-v7 pull request #1826
Opened 2019-10-15 17:02 UTC by shivamkainth

Went to npmjs website, confirmed the latest version from there and then updated in the docs.
URL: https://www.npmjs.com/package/nativescript
Also added the CLI installation reference link.
#1182

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] If there is an issue related with this PR, point it out here.

## What is the current state of the documentation article?

## What is the new state of the documentation article?

Fixes/Implements/Closes #[Issue Number].

2019-10-15 17:20 UTC, shivamkainth commented
@cla-bot check

2019-11-06 11:01 UTC, tsonevn commented
HI @shivamkainth,
Thank you for the provided PR. However, I do not think that referring to a specific CLI version inside the article is the best practice. Perhaps, setting an NPM link to the nativescript package would be a better solution. Then every docs visitor will be able to check which version is the latest.

2019-11-06 11:03 UTC, tsonevn requested changes
Set an NPM link to the nativescript package, instead of a specific version

2019-12-17 07:17 UTC, NickIliev approved these changes

2019-12-17 07:17 UTC, merged