[DO NOT MERGE] Update Theme article
NativeScript/docs-v7 pull request #1847
Opened 2019-11-21 08:27 UTC by NickIliev

Related to [https://github.com/NativeScript/docs/issues/1846](https://github.com/NativeScript/docs/issues/1846)

2019-11-26 10:17 UTC, bundyo commented on docs/ui/theme.md
> +To use the default color scheme (with primary color blue), add the following lines of code to the top of your `app.css` file:
```suggestion
To use the default color scheme (with accent color blue), add the following lines of code to the top of your `app.css` file:
```

2019-11-26 10:18 UTC, bundyo commented on docs/ui/theme.md
> +@import '~@nativescript/theme/css/blue.css'; /* same as default.css */
```suggestion
@import '~@nativescript/theme/css/blue.css';
```

Blue and Default skins are not the same - Default is the old Core skin.

2019-11-26 10:19 UTC, bundyo commented on docs/ui/theme.md
> +> **Note**: [This image](/img/theme/color-schemes-all.png) shows all 13 color schemes on iOS and Android, and can help you decide which color scheme is a good fit for your app.
I don't have access to this image?

2019-11-26 10:22 UTC, bundyo commented on docs/ui/theme.md
> +![light dividers ios](/img/theme/dividers-light-ios.png)
Also can't access this image. Are you sure you commited it?

2019-11-26 10:22 UTC, bundyo commented on docs/ui/theme.md
> +* `hr`: Creates a colored divider.
You might want to mention that the .hr class now adapts to the chosen mode.

2019-11-26 10:36 UTC, bundyo commented on docs/ui/theme.md
> +        <StackLayout class="hr"></StackLayout>
This StackLayout shouldn't be needed - the TextField should have the bottom border already.

2019-11-26 10:36 UTC, bundyo commented on docs/ui/theme.md
> +        <StackLayout class="hr"></StackLayout>
Same here

2019-11-26 10:36 UTC, bundyo commented on docs/ui/theme.md
> +        <StackLayout class="hr" row="1" colSpan="2"></StackLayout>
Same here

2019-11-26 12:25 UTC, bundyo commented on docs/ui/theme.md
> +* `sidedrawer-list-item`: A class name to apply to each item, or link, that appears within your sidedrawer’s content.
There are new classes here.

2019-11-26 12:27 UTC, bundyo commented on docs/ui/theme.md
> +/* The variables are loaded bofire the Core styles */
```suggestion
/* The variables are loaded before the Core styles */
```

2019-11-26 12:28 UTC, bundyo requested changes
Some things need to be fixed, check comments.

2019-11-26 12:29 UTC, NickIliev commented on docs/ui/theme.md
> +> **Note**: [This image](/img/theme/color-schemes-all.png) shows all 13 color schemes on iOS and Android, and can help you decide which color scheme is a good fit for your app.
I' haven't touched this one - the image is present on my side.

2019-11-26 12:29 UTC, NickIliev commented on docs/ui/theme.md
> +![light dividers ios](/img/theme/dividers-light-ios.png)
The image is committed and present in the local build.

2019-11-26 13:46 UTC, NickIliev commented on docs/ui/theme.md
> +/* The variables are loaded bofire the Core styles */
all changes applied

2019-11-26 17:13 UTC, bundyo commented on docs/ui/theme.md
> +    <TextField hint="Option 1"/>
I didn't mean to remove the surrounding StackLayout, but the .hr one.

2019-11-26 17:14 UTC, bundyo commented on docs/ui/theme.md
> +    <TextField/>
Same here.

2019-11-26 17:14 UTC, bundyo commented on docs/ui/theme.md
> +    <GridLayout class="-sides" rows="auto, auto" columns="*,*">
Why remove the .nt-input class?

2019-11-26 17:18 UTC, bundyo commented
Several more comments, the rest is fine.

2019-11-27 07:14 UTC, bundyo approved these changes

2019-11-27 08:11 UTC, merged