Article about Image performance techniques in Android
NativeScript/docs-v7 pull request #776
Opened 2017-05-15 12:08 UTC by NickIliev

Related to [https://github.com/NativeScript/NativeScript/issues/2571#issuecomment-299120495](https://github.com/NativeScript/NativeScript/issues/2571#issuecomment-299120495)

2017-05-15 12:34 UTC, hshristov requested changes

2017-05-15 12:34 UTC, hshristov commented on ui/images-optimisations.md
> +Sometimes when working with multiple large images on devices with low memory we can get OOM exception. To prevent that scenario, in NativeScript 2.5.x and above using the `src` property in Android wi
Bitmap memory stays in Java world and is reclaimed once the Bitmap is no longer in use (e.g. there is no need for Javascript object to be collected).

2017-05-15 12:34 UTC, hshristov commented on ui/images-optimisations.md
> +or if we pass Base64 encoded string, we will load the bitmap in JavaScript which may cause OOM exception due to the synchronization of the garbage collectors (JavaScript and Java).
When using ImageSource or Base64 encoded string the `Bitmap` is transferred to Javascript so it will be release only when Javascript object is reclaimed. Javascript garbage collection happens less frequently than Java garbage collection which leads to OOM.

2017-05-15 12:34 UTC, hshristov commented on ui/images-optimisations.md
> +As an additional feature for Android, NativeScript supports `decodeWidth`, `decodeHeight` and `loadMode` properties. The first two will downsample your image so it will take less memory. With [loadMo
`loadMode` is supported in both android & ios. `decode*` properties are android only for the moment.

2017-05-15 12:34 UTC, hshristov commented on ui/images-optimisations.md
> +As an additional feature for Android, NativeScript supports `decodeWidth`, `decodeHeight` and `loadMode` properties. The first two will downsample your image so it will take less memory. With [loadMo
All `http` requests are loaded `async` no matter the value of `loadMode`.

2017-05-15 12:34 UTC, hshristov commented on ui/images-optimisations.md
> +`Image` will use internal memory and disk cache, so images that are loaded are stored in the memory cache and if they are not needed anymore, they are saved in the disk cache. This way the next time
internal memory and disk cache - implemented only for android at the moment.

2017-05-15 13:25 UTC, NickIliev commented on ui/images-optimisations.md
> +`Image` will use internal memory and disk cache, so images that are loaded are stored in the memory cache and if they are not needed anymore, they are saved in the disk cache. This way the next time
the whole article section is explicitly for Android - added in the final Note disclaimer and in the title itself

2017-05-15 13:25 UTC, NickIliev commented on ui/images-optimisations.md
> +As an additional feature for Android, NativeScript supports `decodeWidth`, `decodeHeight` and `loadMode` properties. The first two will downsample your image so it will take less memory. With [loadMo
disclaimer added few lines below

2017-05-16 12:42 UTC, PetyaSotirova approved these changes
Can we add links to the image API and/or the cookbook? Maybe in a See Also section at the end.
Looks great.

2017-05-17 09:16 UTC, hshristov approved these changes

2017-05-17 09:58 UTC, merged