Property system in NativeScript 3.x.x.
NativeScript/docs-v7 pull request #801
Opened 2017-06-08 07:23 UTC by NickIliev

Article about the property system and creating/migrating UI plugin in NativeScript 3.0.0.
Source code based on [this demo plugin](https://github.com/NickIliev/nativescript-my-button).

2017-06-08 11:42 UTC, hshristov requested changes

2017-06-08 11:42 UTC, hshristov commented on core-concepts/properties.md
> +Being a TypeScript framework, NativeScript uses TypeScript properties. After transpilation, these result in ECMAScript v.5 compliant JavaScript with setter and getter methods to support working with
This sounds out of context to me. What getter & setter methods? What readable & manageable code?
Better remove that fluff :)

2017-06-08 11:42 UTC, hshristov commented on core-concepts/properties.md
> +If the type of the property not `string` we will probably need to specify `valueConverter` and `equalityComparer`. The `valueConverter` will be called if a string value is set to your property (for e
Missing **is**
If the type of the property **isn't**

2017-06-08 11:42 UTC, hshristov commented on core-concepts/properties.md
> +If the type of the property not `string` we will probably need to specify `valueConverter` and `equalityComparer`. The `valueConverter` will be called if a string value is set to your property (for e
to your property
may better as **to this property**

2017-06-08 11:42 UTC, hshristov commented on core-concepts/properties.md
> +There is one more property in the `Property` constructor: `affectsLayout: boolean`. When set to `true` setting new value to this property will trigger a new layout pass. `textProperty` sets `affectsL
There is one more property
**There is one more option**

2017-06-08 11:42 UTC, hshristov commented on core-concepts/properties.md
> +There is one more property in the `Property` constructor: `affectsLayout: boolean`. When set to `true` setting new value to this property will trigger a new layout pass. `textProperty` sets `affectsL
only for `ios`
only when executing on `ios`

2017-06-08 11:42 UTC, hshristov commented on core-concepts/properties.md
> +There is one more property in the `Property` constructor: `affectsLayout: boolean`. When set to `true` setting new value to this property will trigger a new layout pass. `textProperty` sets `affectsL
But `ios` doesn't have
**Because `ios` doesn't have**

2017-06-08 11:42 UTC, hshristov commented on core-concepts/properties.md
> +There is one more property in the `Property` constructor: `affectsLayout: boolean`. When set to `true` setting new value to this property will trigger a new layout pass. `textProperty` sets `affectsL
Because `ios` doesn't have integrated layout system if you know that this property could affect the layout you should specify it in the `Property` constructor.

2017-06-08 11:59 UTC, radeva commented on core-concepts/properties.md
> +The next file is `my-button-base.ts`. In the base file we define all common fields, properties and methods that are applicable for both Android and iOS. At the top of the file we declare our new prop
I would suggest something like "In `my-button-base.ts` we define..." instead of "The next file is `my-button-base.ts`. In the base file"

2017-06-08 11:59 UTC, radeva commented on core-concepts/properties.md
> +```
I would suggest here to keep the naming of the files consistent with the plugin seed. We discussed it in the morning with @vakrilov and decided that the current seed naming is ok. It's not a big deal but I think it will help the users to map the example with the seed. So it's up to you.

2017-06-08 11:59 UTC, radeva commented on core-concepts/properties.md
> +If the type of the property not `string` we will probably need to specify `valueConverter` and `equalityComparer`. The `valueConverter` will be called if a string value is set to your property (for e
"If the type of the property not `string`" -> If the type of the property is not `string` : a missing "is"

2017-06-08 11:59 UTC, radeva commented on core-concepts/properties.md
> +If the type of the property not `string` we will probably need to specify `valueConverter` and `equalityComparer`. The `valueConverter` will be called if a string value is set to your property (for e
Nothing is mentioned about `valueChange`. Although it's self-explanatory maybe it would be nice to have some example about it also.

2017-06-08 13:41 UTC, tjvantoll commented on core-concepts/properties.md
> +Being a TypeScript framework, NativeScript uses TypeScript properties. After transpilation, these result in ECMAScript v.5 compliant JavaScript with setter and getter methods to support working with
I find the transition from “NativeScript uses TypeScript properties” to “This article will guide you through the process of creating basic UI plugins” a little strange.

Are properties only applicable to UI elements? If so, this article should state that. Should readers only care about this article if they’re building user interface plugins? (If so, this article shouldn’t be considered a “core concept”, because only a handful of our users will find this information valuable.

2017-06-08 13:45 UTC, tjvantoll commented on core-concepts/properties.md
> +If the type of the property not `string` we will probably need to specify `valueConverter` and `equalityComparer`. The `valueConverter` will be called if a string value is set to your property (for e
> If the type of the property not `string` we will probably need to specify `valueConverter` and `equalityComparer`.

“Probably” is not a good word to use in documentation 😄 

The docs should spell out exactly when you need `valueConverter` and `equalityComparer`.

2017-06-08 13:47 UTC, tjvantoll commented on core-concepts/properties.md
> +There is one more property in the `Property` constructor: `affectsLayout: boolean`. When set to `true` setting new value to this property will trigger a new layout pass. `textProperty` sets `affectsL
I think I’ve asked this one before: but given the way this paragraph is written I wonder why we wouldn’t just make `affectsLayout: isIOS` the default. Everyone reading this will just do that because we tell them to.

2017-06-08 14:44 UTC, DimitarTachev commented on core-concepts/properties.md
> +    on(event: "tap", callback: (args: EventData) => void, thisArg?: any);
You could also think about using TapEventData instead of the default EventData. The example will make more sense.

2017-06-08 14:58 UTC, tjvantoll reviewed
I left this in a specific comment, but I thought I’d mention this overall too: this feels like an article on how to build UI plugins that happens to be titled “Properties” and put in the “Core Concepts” folder.

Is there a reason that all NativeScript developers need to know about properties? If yes, I think we should start the article with generic property information for non-plugin authors. If no, I think we should rename this article “Building UI Plugins” and put it in the Plugins folder.

2017-06-09 08:14 UTC, PetyaSotirova commented
Not all title headings are with the proper casing, e.g. Platform - **S**pecific **C**ode.
Please use imperative mode wherever possible to avoid ambiguity. For example, this sentence:
"We also provide intellisense when myButton.on method is called so that it is known that a tap event is exposed."
Who is "we" - we who develop the framework or we who are going through this tutorial.

2017-06-09 08:16 UTC, PetyaSotirova requested changes

2017-06-09 08:16 UTC, PetyaSotirova commented on core-concepts/properties.md
> +Being a TypeScript framework, NativeScript uses TypeScript properties. After transpilation, these result in ECMAScript v.5 compliant JavaScript with setter and getter methods to support working with
I'm with TJ here - the content flow feels unnatural as if this article contains two separate topics squished together.

2017-06-09 08:16 UTC, PetyaSotirova commented on core-concepts/properties.md
> +> Note: For more details about the plugin infrastructure in NativeScript refer to [this article]({%slug plugins-infrastructure%}).
What's the purpose of having this here if it is already available in the Plugins article?

2017-06-09 08:16 UTC, PetyaSotirova commented on core-concepts/properties.md
> +The first file `index.d.ts` defines the public API of the control (in our case MyButton).
I'd drop "first" here - the 'index.d.ts file defines...

2017-06-09 08:16 UTC, PetyaSotirova commented on core-concepts/properties.md
> +If the type of the property not `string` we will probably need to specify `valueConverter` and `equalityComparer`. The `valueConverter` will be called if a string value is set to your property (for e
Additionally to what TJ said, I'd change the tense in this paragraph to present simple. The valueConverter IS called when the property is changed.

2017-06-09 08:16 UTC, PetyaSotirova commented on core-concepts/properties.md
> +In this implementation we use singleton listener (for android - `clickListener`) and handler (for ios - `handler`) in order to reduce the need to instantiate native classes and to reduce memory usage
Most of the platform specific code above is documented. There are three important methods:
•	_createNativeView_: Override this method, create and return your nativeView.
•	_initNativeView_: Setup listeners/handlers to the nativeView.
•	_disposeNativeView_: Clear the reference between nativeView and javascript object in this method to avoid memory leaks. Reset the native view to its initial state if you want to reuse that native view later.

In Android, avoid access to native types in the root of the module (note that ClickListener is declared and implemented in a function which is called at runtime). This is specific for the V8 snapshot feature which is generated on a host machine where android runtime is not running. What is important is that if you access native types, methods, fields, namespaces, etc. at the root of your module (e.g. not in a function) your code won't be compatible with V8 snapshot feature. The easiest workaround is to wrap it in a function like in the above initializeClickListener function.

In this implementation, we use singleton listener (for android - clickListener) and handler (for ios - handler) in order to reduce the need to instantiate native classes and to reduce memory usage. If possible it is recommended to use such techniques to reduce native calls.

2017-06-12 10:30 UTC, NickIliev commented on core-concepts/properties.md
> +Being a TypeScript framework, NativeScript uses TypeScript properties. After transpilation, these result in ECMAScript v.5 compliant JavaScript with setter and getter methods to support working with
@tjvantoll, @PetyaSotirova perhaps the focus of this article should be "Creating NativeScript Plugins" and should replace the old UI plugins article? Let me know how you feel about it.

2017-06-12 10:42 UTC, NickIliev commented on core-concepts/properties.md
> +```
@radeva meaning that the users have no need of Info.plist file for iOS when creating plugins via plugin-seed?

2017-06-12 10:57 UTC, NickIliev commented on core-concepts/properties.md
> +> Note: For more details about the plugin infrastructure in NativeScript refer to [this article]({%slug plugins-infrastructure%}).
In the plugins article, we have the detailed explanation of a NativeScript plugin. Here we are showing what the users will need to go step-by-step through the specific article - e.g. where to place their prerequisite files like `my-button.d.ts` or `my-button.android.ts`

2017-06-12 14:17 UTC, NickIliev commented
We have discussed the main purpose of this article and I will re-write it so it will be strictly Property System related and not structured like it is a tutorial for a UI plugin. Closing this PR in favor for upcoming new one.

2017-06-12 14:17 UTC, closed without merging