UI Plugin with {N} Core Modules how-to article
NativeScript/docs-v7 pull request #819
Opened 2017-06-28 18:11 UTC by tbozhikov

The article still uses share link instead of path to an image (we need to change it):
http://jmp.sh/7VQqWde
... and a link to an article which is still in a branch:
https://github.com/NativeScript/docs/blob/tachev/angular-compatible-plugin/plugins/angular-plugin.md

2017-06-28 22:58 UTC, radeva reviewed
The subtitles, I would use the same naming pattern for them like:

Bootstrap Your Plugin
Add the UI bits
Make your plugin Angular compatible 

Or 

Bootstraping..
Adding...
Making...

Check other pieces of the documentation for similar titles.

2017-06-28 22:58 UTC, radeva commented on plugins/ui-plugin-ns.md
> +First things first - you start off from a regular plugin. You can use the [NativeScript plugin seed repo](https://github.com/NativeScript/nativescript-plugin-seed).
Here also you can also refer to the article that TJ wrote about creating plugins. For example: If this is your first plugin check out the more detailed guile for (building plugins)[... slug link...]

2017-06-28 22:58 UTC, radeva commented on plugins/ui-plugin-ns.md
> +First things first - you start off from a regular plugin. You can use the [NativeScript plugin seed repo](https://github.com/NativeScript/nativescript-plugin-seed).
Make sure you add title on top which is h1.
Then the subtitles will be h2. This is a general recommendation I received from Petya for my article.

2017-06-28 22:58 UTC, radeva commented on plugins/ui-plugin-ns.md
> +You need 2 files in that do the job:
There is some typo here ... "You need two files to do the job". Always prefer to write the number with letters when it is used in text and it's one wird.

2017-06-28 22:58 UTC, radeva commented on plugins/ui-plugin-ns.md
> +
Add more description for the filed like :
File 1 - defines/describes/contains/to do this and that

2017-06-28 22:58 UTC, radeva commented on plugins/ui-plugin-ns.md
> +
Probably here in the article you can also explain tgat you register properties in the meme.ts and link to the Properties article which Nick Iliev published recently.

2017-06-28 23:01 UTC, radeva requested changes

2017-06-28 23:01 UTC, radeva commented on plugins/ui-plugin-ns.md
> +slug: ui-plugin-ns
- update the slug according to the article title. This will make the article search engine friendly

2017-06-28 23:01 UTC, radeva commented on plugins/ui-plugin-ns.md
> +Having your UI plugin developed successfully you could easily make it Angular compatible following the steps described in [Supporting Angular in UI Plugins article](https://github.com/NativeScript/do
For links to other articles in the documentation, you can use slug syntax, not full links. Check any article with a link to see the exact syntax. This will prevent broken links in further doc reorganization.

2017-06-28 23:02 UTC, radeva commented
Make sure you add Petya and TJ as reviewers.

2017-06-29 11:53 UTC, PetyaSotirova approved these changes

2017-06-29 11:53 UTC, PetyaSotirova commented on plugins/ui-plugin-composite.md
> +First things first - you start off from a regular plugin. You can refer the [Building Plugins article](/plugins/building-plugins.md) for reference.
Please use slug links instead, as moving the article in another folder will break this. [link text]({%slug building-plugins
%})

2017-06-29 11:53 UTC, PetyaSotirova commented on plugins/ui-plugin-composite.md
> +## Add UI bits
Casing should be "Add UI Bits"

2017-06-29 11:53 UTC, PetyaSotirova commented on plugins/ui-plugin-composite.md
> +You need two files in that can do the job:
You can implement this by creating two files:

* **meme.ts**: Contains properties, the implementation logic, and loads the UI.
* **meme.xml**: Contains the UI and data bindings.

2017-06-29 11:53 UTC, PetyaSotirova commented on plugins/ui-plugin-composite.md
> +Having your UI plugin developed successfully you could easily make it Angular compatible following the steps described in [Supporting Angular in UI Plugins article](/plugins/angular-plugin.md).
({%slug angular-third-party%})

2017-06-29 11:53 UTC, PetyaSotirova commented on plugins/ui-plugin-composite.md
> +## Make your plugin Angular compatible
"Make Your Plugin Angular Compatible"

2017-06-29 13:27 UTC, tjvantoll commented on plugins/ui-plugin-composite.md
> +When writing a plugin that shows some UI, you can take different paths. One of the easiest of them is to use {N} means to biuld the UI, i.e. no calls to native APIs. Thus you can even sometimes avoid
> biuld

build

> platform specific

platform-specific

2017-06-29 15:45 UTC, tjvantoll commented
Looks good! The one thing I’d add is what you mean by the term “composite components” somewhere near the start. Basically you’re just using existing {N} components as building blocks for a more complex component, but it took me a while to understand that.

2017-06-29 15:53 UTC, tjvantoll commented on plugins/ui-plugin-composite.md
> +position: 10
Sorry missed this one. You’ll need to change this number before this PR lands. The top two plugin articles are at positions 10 and 20, so you’ll need a number bigger than that. The hidden UI article is at 30 right now, so you could probably use 30 or something near that.

2017-07-03 08:48 UTC, radeva approved these changes

2017-07-03 09:06 UTC, merged