Tbozhikov/ui plugin custom
NativeScript/docs-v7 pull request #828
Opened 2017-07-04 13:02 UTC by tbozhikov

- new article about Building UI Plugins Using Custom Components
- fixes in the article Building UI Plugins Using Composite Components

2017-07-05 10:06 UTC, radeva requested changes

2017-07-05 10:06 UTC, radeva commented on plugins/ui-plugin-custom.md
> +* [Add the UI bits: common code](#add-the-ui-bits-common-code)
you can use h3 for "common-code" and "specific code" i.e.:
## Add the UI Bits
### Common Code
### Platform Specific Code

2017-07-05 10:06 UTC, radeva commented on plugins/ui-plugin-custom.md
> +The article contains information applicable to apps built on NativeScript 3.x.x or newer version
I think the correct is "built with" instead of "built on"

2017-07-05 10:06 UTC, radeva commented on plugins/ui-plugin-custom.md
> +- **my-button.d.ts** - to hold the declarations of MyButton class, its properties "text" and "myOpacity", enables auto-complete in some IDEs.
keep the same formatting in the explanation. below "holds" is used which I think is better.

2017-07-05 10:06 UTC, radeva commented on plugins/ui-plugin-custom.md
> +- **my-button.ios.ts** - holds the iOS-specific logic for creation the native view (UIButton)
"for creation the native view" -> "for creation of the native view"

2017-07-05 10:06 UTC, radeva commented on plugins/ui-plugin-custom.md
> +
Is there an article or blog post about snapshots? If there is, you can link it here.

2017-07-05 10:06 UTC, radeva commented on plugins/ui-plugin-custom.md
> +In the a.m. implementations we use singleton listener (for Android - `clickListener`) and handler (for iOS - `handler`) in order to reduce the need to instantiate native classes and to reduce memory
What is "a.m." ?

2017-07-05 16:53 UTC, tbozhikov commented on plugins/ui-plugin-custom.md
> +In the a.m. implementations we use singleton listener (for Android - `clickListener`) and handler (for iOS - `handler`) in order to reduce the need to instantiate native classes and to reduce memory
"a.m." = above mentioned
:)

2017-07-06 14:50 UTC, radeva approved these changes

2017-07-06 14:51 UTC, merged