Add more documentation for V8 Heap Snapshot feature
NativeScript/docs-v7 pull request #830
Opened 2017-07-05 15:18 UTC by ivanbuhov

Add more documentation for:
 * `tnsJavaClassesOptions` configuration (FYI: @sis0k0 )
 * `global.__snapshot`, `global.__snapshotEnabled` flags
 * `genrate-android-snapshot` npm script

2017-07-06 12:28 UTC, PetyaSotirova requested changes

2017-07-06 12:28 UTC, PetyaSotirova commented on best-practices/bundling-with-webpack.md
> +* `tnsJavaClassesOptions` - Basically, every Java class successor, declared in NativeScript, consists of two parts - native Java part generated by the static binding generator and JavaScript counterp
Every Java class successor declared in NativeScript, consists of two parts - a native Java part generated by the static binding generator and a JavaScript counterpart,...
Who is "we" in the next sentence? Please rephrase as it is a bit confusing.

2017-07-06 12:28 UTC, PetyaSotirova commented on best-practices/bundling-with-webpack.md
> +    1. The static binding generator saves in the class metadata the path to the file containing its JavaScript implementation.
Reverse the word order - saves the path in the class...

2017-07-06 12:28 UTC, PetyaSotirova commented on best-practices/bundling-with-webpack.md
> +    If you are a plugin author and your plugin contains such modules that have to be listed here, you can [specify it in your plugin's `package.json` file](https://github.com/NativeScript/NativeScrip
Either "contains a module" or "specify them"

2017-07-06 12:28 UTC, PetyaSotirova commented on best-practices/bundling-with-webpack.md
> +If you have logic that you want (not) to be executed only in snapshotted context you can check the `global.__snapshot` flag. Its value is `true` only if the current execution happens in the snapshott
If you want to toggle whether specific logic is executed only in snapshot context, you can...

2017-07-06 13:07 UTC, sis0k0 requested changes

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +Using snapshot without Webpack is not a common scenario. Packing all scripts into one fat bundle, in advance, is what makes the snapshot so beneficial. Generating snapshot for a single script only wi
`genrate-android-snapshot` -> `generate-android-snapshot`

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +Using snapshot without Webpack is not a common scenario. Packing all scripts into one fat bundle, in advance, is what makes the snapshot so beneficial. Generating snapshot for a single script only wi
Maybe, it will be better to start with how to do it and then explain that it's not a common scenario.

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +* `tnsJavaClassesOptions` - Basically, every Java class successor, declared in NativeScript, consists of two parts - native Java part generated by the static binding generator and JavaScript counterp
- Add link to the SBG docs -
 https://docs.nativescript.org/runtimes/android/generator/overview
- `we should make sure that the it is evaluated` -> `we should make sure that it is evaluated `

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +    This doesn't work in bundling scenario, because the saved path in the metadata always points to the bundle. However, executing the bundle script will not achieve the desired result. Therefore, we
`However, executing the bundle script will not achieve the desired result.`
Shall we explain why?

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +    This doesn't work in bundling scenario, because the saved path in the metadata always points to the bundle. However, executing the bundle script will not achieve the desired result. Therefore, we
`vendor-platform.android.js` -> `app/vendor-platform.android`

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +    However, when we add the V8 heap snapshot in the whole story, we are not allowed to extend native classes in snapshotted context. Therefore, we always include `ui/frame` and `ui/frame/activity` i
``the `tns-java-classes.js` files`` -> ``the `tns-java-classes.js` file``

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +    plugins.push(new nsWebpack.NativeScriptSnapshotPlugin({
drop plugins.push

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +    If you are a plugin author and your plugin contains such modules that have to be listed here, you can [specify it in your plugin's `package.json` file](https://github.com/NativeScript/NativeScrip
Let's inline the example configuration in the docs instead of link to a commit.

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +    plugins.push(new nsWebpack.NativeScriptSnapshotPlugin({
drop plugins.push

2017-07-06 13:07 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +If you have logic that you want (not) to be executed only in snapshotted context you can check the `global.__snapshot` flag. Its value is `true` only if the current execution happens in the snapshott
Explain what's snapshotted context.

2017-07-07 08:47 UTC, PetyaSotirova approved these changes

2017-07-07 09:32 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +The webpack configuration also includes the [`NativeScriptSnapshotPlugin`](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/plugins/NativeScriptSnapshotPlugin.js). The plugin load
typo
`snapshtted` -> `snapshotted`

2017-07-07 09:33 UTC, sis0k0 commented on best-practices/bundling-with-webpack.md
> +The `nativescript-dev-webpack` plugin adds `generate-android-snapshot` npm script in the app's `package.json` file. The command will check if `__snapshot.js` file exists in the app root folder and wi
`into one fat bundle, in advance`, drop the comma?

2017-07-07 11:38 UTC, sis0k0 approved these changes

2017-07-07 11:40 UTC, merged