Add unit tests article for plugins
NativeScript/docs-v7 pull request #841
Opened 2017-07-12 12:07 UTC by zbranzov

2017-07-12 12:24 UTC, radeva requested changes

2017-07-12 12:24 UTC, radeva commented on plugins/unit-tests.md
> +environment: nativescript
If the article is relevant to both nativescript and angular, remove the environment

2017-07-12 12:24 UTC, radeva commented on plugins/unit-tests.md
> +Writting unit tests for a plugin that is developed using the [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed) is as simple as building the plugin itself. Before we
typo: Writting -> Writing

2017-07-12 12:24 UTC, radeva commented on plugins/unit-tests.md
> +
"The whole structure comes after you init" - I'm not sure how this sounds for native speakers. @tjvantoll can confirm if it is ok. My suggestion is 'The whole test structure comes for you out of the box when you init your..."

2017-07-12 12:24 UTC, radeva commented on plugins/unit-tests.md
> +By starting from the [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed) you get out of the box fully functional `.travis.yml` file ready to run your unit tests on An
At the end you can link the article "Ensure Plugins Quality": https://github.com/NativeScript/docs/blob/master/plugins/ensure-plugins-quality.md

2017-07-12 14:41 UTC, tjvantoll reviewed
Looks good. One note: can you change the “Adding unit tests” link at the bottom of https://docs.nativescript.org/plugins/building-plugins to point at this article?

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +description: A guide describing how easy is to write unit tests for plugin created using nativescript-plugin-seed.
how easy it is to write unit tests for plugins created using the NativeScript plugin seed.

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +slug: unit-tests
Probably want to go with plugin-unit-tests here.

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +You have completed your plugin and it works great, but how you can be sure that every other change applied to the code base will not break some functionality and how to easily check plugin's state. H
check a plugin’s state

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +The starting point of writting unit tests is the `tests` folder in your demo app directory. There you will find `tests.js` file containing sample [Jasmine](https://jasmine.github.io/) tests.
writting --> writing

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +
The current wording is ok. I get what you mean and that’s the most important thing. Since you asked though, this is how I would personally word this:

The NativeScript plugin seed builds this structure automatically when you initialize your plugin, so don’t worry about creating these files and folders manually.

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +Let's write a few additional tests to default ones as a showcase. We will continue from the point where [Building UI Plugins Using Composite Components]({% building-ui-plugins-composite-components %}
Let’s add a few additional tests to the `tests.js` file.

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +Every test assigns a value to the property in testing and verifies that the same value is applied to the element in the visual tree that uses it. I guess you wonder how I know the indexes of the elem
> I guess you wonder how I know the indexes of the elements selected with `getChildAt()` function.

I would rephrase this to explain what `getChildAt()` does and link to the API documentation.

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +The complete `test.js` file you can find [here](https://github.com/NativeScript/nativescript-ui-plugin/blob/master/demo/app/tests/tests.js).
You can find the complete `tests.js` file here.

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +> **NOTE**: Using the npm scripts to run your tests is the best option, but in case of debugging purposes, where you want to output some console logs, you will have to navigate to `demo` folder and r
to your `demo` folder

2017-07-12 14:41 UTC, tjvantoll commented on plugins/unit-tests.md
> +By starting from the [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed) you get out of the box fully functional `.travis.yml` file ready to run your unit tests on An
you get an out-of-the-box fully-functional `.travis.yml` file

activate your repository, and make sure `Build pushes` and `Build pull requests` are enabled

2017-07-12 15:53 UTC, zbranzov commented on plugins/unit-tests.md
> +environment: nativescript
@radeva not sure about angular so will leave it this way for now

2017-07-13 14:59 UTC, radeva approved these changes

2017-07-13 14:59 UTC, merged