update article to include a more decend way of debugging
NativeScript/docs-v7 pull request #934
Opened 2017-10-09 13:44 UTC by Plamen5kov

2017-10-10 06:42 UTC, tsonevn approved these changes

2017-10-10 07:26 UTC, etabakov requested changes
I think this section is getting messy. We have three ways to debug an application and we are showcasing the most primitive and least preferable one. Isn't it better to change the title of the current one to "Logging" and create a new section for debugging with Chrome Dev Tools?

@tjvantoll What do you think about this?

2017-10-10 12:19 UTC, tjvantoll commented on docs/tutorial/ng-chapter-1.md
> +One of the preffered ways of debugging a NativeScript application is with the [NativeScript extension for Visual Studio Code](http://docs.nativescript.org/tooling/debugging#debugging-with-visual-stud
preferred

2017-10-10 12:25 UTC, tjvantoll commented on docs/tutorial/ng-chapter-1.md
> +The default way of debugging a NativeScript application is by using the integration with Chrome. You can find more information on the actual steps [here](http://docs.nativescript.org/tooling/debuggin
I worry that you set readers up for failure by just linking to that page and not walking them through exactly how to use the Chrome Dev Tools. For example, the Chrome Dev Tools only work in iOS if you use the `--chrome` flag, and that fact is barely mentioned.

2017-10-10 12:45 UTC, tjvantoll commented on docs/tutorial/ng-chapter-1.md
> +The default way of debugging a NativeScript application is by using the integration with Chrome. You can find more information on the actual steps [here](http://docs.nativescript.org/tooling/debuggin
I think this will be ok if you mention it after the `console.log()` example though, because then it’s kind of an aside for readers to check out when they’re ready.

2017-10-10 12:48 UTC, tjvantoll reviewed
Long term I think this tutorial should actually walk the user through running the appropriate commands and teach them the Dev Tools with examples, as @etabakov suggests. The next iteration of the tutorial that Jen & I are thinking through now will almost certainly do that.

Until then I don’t mind mentioning these tools, but I’d kind of like this PR’s wording to be put _after_ the `console.log` example—just because I think it’ll flow better. Right now it’s a bit weird to say, “here are the best two ways to debug your apps but we’re not going to use them”.

`console.log()` is basic, _but_ it’s something the reader can do without installing something new, and without having to stop their app from running with `Ctrl` + `C` and learning a new `debug` command with a `--chrome` flag.

That’s my thoughts at least. If you just replace the sentences below with what you have here I think this should be good for now. (Also remember that there are two tutorials, so there’s a `chapter-1.md` file with this same wording.)

> “The console.log() and console.dir() functions are two of the many tools available when debugging your NativeScript applications. You might want to try out step debugging as you move into more advanced development”

2017-10-10 14:23 UTC, Plamen5kov commented on docs/tutorial/ng-chapter-1.md
> +The default way of debugging a NativeScript application is by using the integration with Chrome. You can find more information on the actual steps [here](http://docs.nativescript.org/tooling/debuggin
@tjvantoll I don't think we're setting anyone up for failure when we're pointing them to a specific article about debugging. The fact that ios debugging in chrome is working with the `--chrome` flag is one of the first things, mentioned in the article.
Furthermore, I don't think console.log is actual debugging. On this point, I think more like @etabakov : let's have a logging section, but not call console.log .. debugging.

2017-10-10 14:29 UTC, Plamen5kov commented
@tjvantoll I understand what you're saying, but here's what I see.
I go and look at the tutorial, which says that debugging === console.log and in the bottom, there's something about vs code extension, which I may or may not be using and not a word for real debugging on chrome and safari.
I suggest having a debugging section with a simple link to debugging article and logging section which suggests using console.log.

> “here are the best two ways to debug your apps but we’re not going to use them”
On this concern: we can just say for the sake of understanding the flow of the application, we can use console.log, which won't be misleading IMO.

2017-10-10 17:59 UTC, tjvantoll commented
@Plamen5kov Ok that makes sense. I think as long as you add some wording that makes what you have in this PR flow into the `console.log` example we’ll be good.

So I’d add something like...

_You’ll want to check out the Chrome Dev Tools and the Visual Studio debugger as you have the need to step through your JavaScript code or TypeScript code, but for the moment let’s look at how to do some simple logging in your apps._

2017-10-10 18:02 UTC, tjvantoll commented on docs/tutorial/ng-chapter-1.md
> +The default way of debugging a NativeScript application is by using the integration with Chrome. You can find more information on the actual steps [here](http://docs.nativescript.org/tooling/debuggin
I think having a different section eventually makes a lot of sense, but I’d be hesitant to add a section that just has two links.

You’ve convinced me that the wording you currently have is worth moving forward with. I just want a bit of text to transition from Chrome/VS Code into the `console.log` examples and 👍  from me.

2017-10-11 13:05 UTC, tjvantoll commented
@Plamen5kov It’s “preferred” (two _r_ s) 😉 

Update that and 👍  from me on merging this in.

2017-10-11 14:04 UTC, Plamen5kov commented
my bad

2017-10-12 06:26 UTC, etabakov approved these changes

2017-10-12 06:36 UTC, merged